diable str + fix

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -7,7 +7,7 @@ variables:
   - name: kibanaBaseVersion # kibana version
     value: "8.12"
   - name: pluginPatchVersion # patch version of the plugin
-    value: ""
+    value: "2"
   - name: pluginVersion # version of the plugin
     value: "" # "$(kibanaBaseVersion).$(pluginPatchVersion)"
   
@@ -36,18 +36,18 @@ steps:
     cd plugins/$(pluginName)
     ls -la
     # Parse the Json file and get the values.
-    plugin_version=$(cat kibana.json | jq -r '.example.value1')
+    plugin_version=$(cat kibana.json | jq -r '.version')
     # split version to get kibana version and patch level
     IFS=. read -a version_parts <<< "$plugin_version"
     echo "##[debug] Found ${#version_parts[@]} parts in version"
-    if [ ${#version_parts[@]} -ne 3 ]; then
-      echo "##[error] Version must have 3 parts, found ${#version_parts[@]}"
-      exit 1
-    fi
+    # if [ ${#version_parts[@]} -ne 3 ]; then
+    #  echo "##[error] Version must have 3 parts, found ${#version_parts[@]}"
+    #  exit 1
+    # fi
     # Set the values as output variables.
     echo "##vso[task.setvariable variable=pluginVersion;isoutput=true]$plugin_version"
-    echo "##vso[task.setvariable variable=kibanaBaseVersion;isoutput=true]${version_parts[0]}.${version_parts[1]}"
-    echo "##vso[task.setvariable variable=pluginPatchVersion;isoutput=true]$version_parts[2]"
+    # echo "##vso[task.setvariable variable=kibanaBaseVersion;isoutput=true]${version_parts[0]}.${version_parts[1]}"
+    # echo "##vso[task.setvariable variable=pluginPatchVersion;isoutput=true]$version_parts[2]"
     cd ../..
   displayName: 'Get Version'
 - task: UseNode@1
